version: '3'
services:
  db: 
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_DATABASE: 'LEARNHUB'
      MYSQL_USER: 'this_user'
      MYSQL_PASSWORD: '123'
    volumes: 
      - ./data:/var/lib/mysql